name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      plugins: ${{ steps['set-plugins'].outputs.plugins }}
    steps:
      - uses: actions/checkout@v2
      - id: set-plugins
        run: echo "::set-output name=plugins::$(jq -cM .packages lerna.json)"
  lint:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - run: brew install swiftlint
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/checkout@v2
      - name: Restore Dependency Cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-dependency-cache-${{ hashFiles('**/package.json') }}
      - run: npm install
      - run: npm run lint
  verify:
    runs-on: macos-latest
    timeout-minutes: 30
    needs:
      - set-matrix
      - lint
    strategy:
      matrix:
        plugin: ${{ fromJson(needs['set-matrix'].outputs.plugins) }}
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/checkout@v2
      - name: Restore Dependency Cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-dependency-cache-${{ hashFiles('**/package.json') }}
      - run: npm install
      - run: npm run verify
        working-directory: ${{ matrix.plugin }}
  deploy:
    runs-on: macos-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    timeout-minutes: 30
    needs:
      - lint
      - verify
    steps:
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/checkout@v2
      - name: Restore Dependency Cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-dependency-cache-${{ hashFiles('**/package.json') }}
      - run: npm install
      - run: npx lerna publish from-git --yes
